export const chartColors = {
  axis: "var(--color-axis)",
  grid: "var(--color-grid)",
  tooltipBg: "var(--color-tooltip-bg)",
  tooltipBorder: "var(--color-tooltip-border)",
  fg: "var(--color-fg)",
  fgMuted: "var(--color-fg-muted)",
  fgSubtle: "var(--color-fg-subtle)",
  fgFaint: "var(--color-fg-faint)",
  cursorFill: "rgba(15, 23, 42, 0.04)",
  cursorStroke: "var(--color-fg-faint)",
  drain400: "var(--color-drain-400)",
  drain500: "var(--color-drain-500)",
  drain600: "var(--color-drain-600)",
  cool400: "var(--color-cool-400)",
  cool500: "var(--color-cool-500)",
  cool600: "var(--color-cool-600)",
  pool: "var(--color-pool)",
  overshoot: "var(--color-overshoot)",
  budget: "#8b5cf6",
} as const;
