services:
  drainspotter:
    container_name: drainspotter
    build:
      context: .
      dockerfile: Containerfile
    restart: unless-stopped
    healthcheck:
      test: nc -z 127.0.0.1 80 || exit 1
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
    expose:
      - 80
    networks:
      - traefik
    labels:
      com.centurylinklabs.watchtower.enable: "false"
      traefik.enable: "true"
      traefik.http.routers.drainspotter.rule: "Host(`drainspotter.example.com`)"
      traefik.http.routers.drainspotter.entrypoints: "websecure"
      traefik.http.routers.drainspotter.tls.certresolver: "letsencrypt"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"

networks:
  traefik:
    name: traefik
    external: true
